# Taken from https://github.com/marketplace/actions/deploy-to-github-pages

name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install and Build 🔧
        run: |
          sudo apt install -y xmlstarlet
          npm install
          npm install -g node-gyp
          cd style && make sprites

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: style/ # The folder the action should deploy.
